- id: '1658030651655'
  alias: Bedside Light Dim Control
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 7fe49afed3dcf831f98f95cb3a9eee3f
    type: action
    subtype: single
    discovery_id: 0x00158d0007edb8a9 action_single
    id: on_press
    enabled: true
  - platform: device
    domain: mqtt
    device_id: 7fe49afed3dcf831f98f95cb3a9eee3f
    type: action
    subtype: release
    discovery_id: 0x00158d0007edb8a9 action_release
    id: on_release
  - platform: device
    domain: mqtt
    device_id: 7fe49afed3dcf831f98f95cb3a9eee3f
    type: action
    subtype: hold
    discovery_id: 0x00158d0007edb8a9 action_hold
    id: on_hold
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: on_press
      sequence:
      - service: light.toggle
        data:
          brightness: 70
          transition: 1
        target:
          entity_id: light.timbedsidelight
    - conditions:
      - condition: trigger
        id: on_hold
      sequence:
      - service: input_boolean.turn_on
        data: {}
        target:
          entity_id:
          - input_boolean.bedsidelightdimstatus
      - if:
        - condition: state
          entity_id: input_boolean.dimswitchstate
          state: 'on'
        then:
        - repeat:
            while:
            - condition: state
              entity_id: input_boolean.bedsidelightdimstatus
              state: 'on'
            sequence:
            - service: light.turn_on
              data:
                brightness_step: 3
              target:
                entity_id: light.timbedsidelight
            - delay:
                hours: 0
                minutes: 0
                seconds: 0
                milliseconds: 70
        else:
        - repeat:
            while:
            - condition: state
              entity_id: input_boolean.bedsidelightdimstatus
              state: 'on'
            sequence:
            - service: light.turn_on
              data:
                brightness_step: -3
              target:
                entity_id: light.timbedsidelight
            - delay:
                hours: 0
                minutes: 0
                seconds: 0
                milliseconds: 70
    - conditions: []
      sequence:
      - choose:
        - conditions:
          - condition: trigger
            id: on_release
          sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
              - input_boolean.bedsidelightdimstatus
          - service: input_boolean.toggle
            data: {}
            target:
              entity_id: input_boolean.dimswitchstate
        default: []
    default: []
  mode: parallel
  max: 3
